site_name: roms4me
site_description: A cross-platform ROM organizer and verifier
theme:
  name: material
  palette:
    - scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - ROM Directory Format: rom-directory-format.md
