"""add prescan info table

Revision ID: 1b54ec1f95ae
Revises: 1bab97f946df
Create Date: 2026-03-30 15:39:06.312442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1b54ec1f95ae'
down_revision: Union[str, Sequence[str], None] = '1bab97f946df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prescaninfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('rating', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dat_game_count', sa.Integer(), nullable=False),
    sa.Column('dat_extensions', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rom_file_count', sa.Integer(), nullable=False),
    sa.Column('rom_extensions', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_matches', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prescaninfo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prescaninfo_system_id'), ['system_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescaninfo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prescaninfo_system_id'))

    op.drop_table('prescaninfo')
    # ### end Alembic commands ###
