"""add log field to scanmeta

Revision ID: 1bab97f946df
Revises: 913be2696d5c
Create Date: 2026-03-30 13:57:28.586922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1bab97f946df'
down_revision: Union[str, Sequence[str], None] = '913be2696d5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scanmeta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('log', sqlmodel.sql.sqltypes.AutoString(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scanmeta', schema=None) as batch_op:
        batch_op.drop_column('log')

    # ### end Alembic commands ###
