"""initial schema

Revision ID: 3935330e4199
Revises: 
Create Date: 2026-03-30 12:07:16.254324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3935330e4199'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_name'), ['name'], unique=True)

    op.create_table('datpath',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('datpath', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_datpath_path'), ['path'], unique=False)
        batch_op.create_index(batch_op.f('ix_datpath_system_id'), ['system_id'], unique=False)

    op.create_table('rompath',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rompath', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rompath_path'), ['path'], unique=False)
        batch_op.create_index(batch_op.f('ix_rompath_system_id'), ['system_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rompath', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rompath_system_id'))
        batch_op.drop_index(batch_op.f('ix_rompath_path'))

    op.drop_table('rompath')
    with op.batch_alter_table('datpath', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_datpath_system_id'))
        batch_op.drop_index(batch_op.f('ix_datpath_path'))

    op.drop_table('datpath')
    with op.batch_alter_table('system', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_name'))

    op.drop_table('system')
    # ### end Alembic commands ###
