"""add note field to scanresult

Revision ID: 972fe5226db6
Revises: 1b54ec1f95ae
Create Date: 2026-03-30 20:19:57.381463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '972fe5226db6'
down_revision: Union[str, Sequence[str], None] = '1b54ec1f95ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scanresult', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scanresult', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###
