"""add plan field to scanresult

Revision ID: f4ec9632e55b
Revises: 972fe5226db6
Create Date: 2026-03-30 22:33:48.721299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f4ec9632e55b'
down_revision: Union[str, Sequence[str], None] = '972fe5226db6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scanresult', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan', sqlmodel.sql.sqltypes.AutoString(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scanresult', schema=None) as batch_op:
        batch_op.drop_column('plan')

    # ### end Alembic commands ###
